### ISSUE TITLE
KiCad's access to InvenTree's part's name upon BOM import to InvenTree

### ISSUE THREAD

**Issue by JacobEFO** [afkiwers/inventree-kicad-plugin#102]
Hi afkiwers,

I am currently using your plugin here, to easily interact between InvenTree  and KiCad. However, I have run into a problem when I export a KiCad BOM that I then wish to import back into InvenTree.

The components I place via the `inventree_kicad` plugin correctly have the right metadata except for the actual part name as given in InvenTree. Take for instance an LED I am using defined as this in InvenTree:

<img width="1675" alt="image" src="https://github.com/user-attachments/assets/6ebf6a07-2b13-4c75-9d9f-8d6f133a7b00">

And the appearance in KiCad.
<img width="1124" alt="image" src="https://github.com/user-attachments/assets/dbc22862-0a94-431f-801a-555742acd3a4">

And how it appears in the KiCad exported BOM:
<img width="718" alt="image" src="https://github.com/user-attachments/assets/1bb279ae-8905-49e1-94b8-e9b6ffa59be6">

To correctly import a KiCad BOM InvenTree requires a `Component` column which I cannot figure out how `inventree_kicad` handles. You can see here a snip of the InvenTree BOM import window:
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/23a21553-cc59-45d4-bfb8-baff8e92d78d">

Have you done something similar or do you have any idea how to easily resolve this issue? My own go-to would be to use my `IPN` and retrieve the corresponding component names and add that as an extra column. But this seems slightly excessive. A good option could be that `inventree_kicad` adds a component field such as `Inventree_Part` taken as the part name of each component.

**Comment by afkiwers** [comment]
Perfect, I'm glad it works now.
