### ISSUE TITLE
Unable to configure plugin and set library categories

### ISSUE THREAD

**Issue by JacobEFO** [afkiwers/inventree-kicad-plugin#79]
Hi,

I recently installed the inventree_kicad plugin and have some troubles following the setup guide. When I reach the step where I am supposed to find `KicadLibraryPlugin` I find `Kicad Library Endpoint` instead:
<img width="306" alt="image" src="https://github.com/afkiwers/inventree_kicad/assets/22648097/1e32e502-d567-41a8-ae81-d7af8c12c0a8">

In here I don't quite find the right options to proceed with the setup. However, I do find the section here that talks a little about `kicad-library-list`, for which I get lead to a JSON formatted text file:
<img width="1339" alt="image" src="https://github.com/afkiwers/inventree_kicad/assets/22648097/0913fba5-5990-4fd8-ba70-0c432dc8bf3c">

I am fairly certain I restarted the container and migrated it correctly, albeit there is naturally room for error.

For reference:

I run inventree_kicad version 1.3.15

And inventree Version Information:
InvenTree-Version: 0.13.5
Django Version: 3.2.23
Commit Hash: 0804ecf
Commit Date: 2024-02-05

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.4.16-linuxkit-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'KiCadLibraryPlugin', 'slug': 'kicad-library-plugin', 'version': '1.3.15'}]

**Comment by afkiwers** [comment]
Hi Jacob,You did everything needed to install the plugin so that's done!

Next step is to head to the admin panel and add some categories you'd like to see in KiCad.

The URLs you see under settings are a standard display which comes from InvenTree; you can just ignore those ones.

I'll wirk on the instructions so that there is less confusion.

Please let me know how you go!

**Comment by afkiwers** [comment]
I am happy to have a look at that. It just means that I need to find a way to implement that without adding more switches.

Feel free to add a FR issue
