### ISSUE TITLE
Question on the Kicad http-lib interaction with inventree_kicad

### ISSUE THREAD

**Issue by JacobEFO** [afkiwers/inventree-kicad-plugin#94]
Hi afkiwers,

Now I am not well versed on the interaction between Kicad via the HTTP library and inventree, but I do have two questions.

**First Question**
When accessing components from Inventree via Kicad's HTTP library, the component name from Inventree will in Kicad be used both as `item` and `description`. See for instance my example with a resistor:
<img width="756" alt="image" src="https://github.com/afkiwers/inventree_kicad/assets/22648097/cc9dc9c5-9774-4a54-8c37-7977f4ea30da">

Here it nicely illustrates that my component name `CRCW08051K00FK` is used as both `item` and `description`. While you can search for what is given in the component's actual description, it is superfluous to have the component name twice in the same sparse overview. Is there any way I can control this, perhaps via the Kicad HTTPlib file.

**Second Question**
When including IPN from the `KiCad Library Endpoint`, the `IPN` will always appear dead center in the component, as illustrated below:
<img width="475" alt="image" src="https://github.com/afkiwers/inventree_kicad/assets/22648097/f2fe7374-7995-488e-b98f-11cf3e1c40d8">

If I were to add `IPN` as a field in the symbol referenced (here an 'R'), the HTTP will just ignore its placement and add a second field to said component.

Can I somehow control this functionality, so I can have all my symbols pre-define where the `IPN` should appear, so I don't have to drag `IPN` around for all my instantiations?

**Comment by afkiwers** [comment]
Hi @JacobEFO,

what version of the plugin are you using?

Would you be able to provide a screenshot of your settings, like this one here?

![image](https://github.com/afkiwers/inventree_kicad/assets/42826581/3ff3deea-6d3b-403e-bf5b-ce07c89c0a9e)

**Comment by afkiwers** [comment]
Regarding your IPN location issue. KiCad does not accept coordinates for any fields. However, what you can do is modify the R symbol and add a Field called IPN to it like below.

![image](https://github.com/afkiwers/inventree_kicad/assets/42826581/f7a8c417-4efa-4e6d-b7ae-7eb496384257)

KiCad will then simply override the field with the new value. Please not that you will see IPN twice inside the symbol chooser dialog; however, only the most recent one is carried over into the schematic.

![image](https://github.com/afkiwers/inventree_kicad/assets/42826581/e1d2cfbe-2d93-4737-bab7-9cc62b3a2948)


![image](https://github.com/afkiwers/inventree_kicad/assets/42826581/3aacceec-7837-4aef-b6aa-48654f4d6db7)

**Comment by afkiwers** [comment]
It does work for me with the latest KiCad version.I am not sure what your KiCad is doing though.

If you added that field and saved it, then it should be there.

Have you tried to place it as raw symbol R (not from InvenTree) and checked that the IPN shows up where it is supposed to be?

**Comment by afkiwers** [comment]
Windows
